excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rhsimplex.github.io
title: Puns & Fingerguns
tagline: Having a lovely data
description: Ryan's Blog
paginate: 5
google_analytics: UA-69382607-1
